name: CodeGuard CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v3

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install Dependencies
      run: |
        pip install requests
        sudo apt-get update
        sudo apt-get install -y jq

    - name: 📤 Send Code to AI
      id: ai_step
      run: |
        git fetch origin main

        CHANGED_FILES=$(git diff --name-only origin/main...HEAD)

        echo "Changed files:"
        echo "$CHANGED_FILES"

        CODE=""
        for file in $CHANGED_FILES; do
         if [[ -f "$file" ]]; then
           echo "Reading $file"
           CONTENT=$(cat "$file")
           CODE="$CODE\n\nFile: $file\n$CONTENT"
         fi
        done

        CODE_JSON=$(echo "$CODE" | jq -Rs .)
  
        RESPONSE=$(curl -s -X POST "https://codeguard-qid9.onrender.com/review" \
          -H "Content-Type: application/json" \
          -d "{\"code\": $CODE_JSON}"

        echo "Response: $RESPONSE"

        SEVERITY=$(echo $RESPONSE | jq -r '.severity')
        ISSUES_COUNT=$(echo $RESPONSE | jq '.issues | length')

        echo "severity=$SEVERITY" >> $GITHUB_OUTPUT
        echo "issues=$ISSUES_COUNT" >> $GITHUB_OUTPUT
        echo "response=$RESPONSE" >> $GITHUB_OUTPUT

        if [ -z "$SEVERITY" ] || [ "$SEVERITY" = "null" ]; then
          echo "❌ Invalid AI response. Failing pipeline."
          exit 1
        fi

        if [ "$SEVERITY" = "critical" ]; then
          echo "❌ Critical issues found. Blocking merge."
          exit 1

        elif [ "$SEVERITY" = "high" ]; then
          echo "⚠️ High severity issues found. Proceed with caution."

        else
          echo "✅ Code acceptable."
        fi

        if [ "$ISSUES_COUNT" -gt 5 ]; then
          echo "❌ Too many issues. Failing pipeline."
          exit 1
        fi

    - name: 💬 Comment on PR
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        COMMENT_BODY="### 🔍 CodeGuard Analysis\n\n"
        COMMENT_BODY+="**Severity:** ${{ steps.ai_step.outputs.severity }}\n\n"
        COMMENT_BODY+="**Issues Found:** ${{ steps.ai_step.outputs.issues }}\n\n"
        COMMENT_BODY+="### Full Response:\n${{ steps.ai_step.outputs.response }}"

        curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -X POST \
          -d "{\"body\": \"$COMMENT_BODY\"}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
